import type { Metadata } from "next";
import {  Figtree } from "next/font/google";
import "./globals.css";


const defaultFont = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${defaultFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
